# Generated by Django 4.0.4 on 2022-06-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mothie',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mothie',
            name='reply',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
